In [1]:
import numpy as np

In [2]:
# Matriz identidade
I = np.eye(3)
# matriz de permutação
Y = np.random.permutation(I)
print(f'I: {I}')
print(f'Y: {Y}')

I: [[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
Y: [[0. 0. 1.]
 [1. 0. 0.]
 [0. 1. 0.]]
